reorganized the BlockFile class in anticipation of supporting compressed blocks.

diff --git a/sf-cvs/trunk/audacity-old/configure b/sf-cvs/trunk/audacity-old/configure
--- a/sf-cvs/trunk/audacity-old/configure
+++ b/sf-cvs/trunk/audacity-old/configure
@@ -2899,7 +2899,7 @@ EOF
 fi
 
 CFLAGS=""
-CPPFLAGS="-O3"
+CPPFLAGS=""
 CXXFLAGS=""
 
 # Check whether --enable-debug or --disable-debug was given.
@@ -3266,14 +3266,16 @@ fi
 debugstring="non-debugging"
 wxconfig="wxgtk-config"
 if [ $enable_debug = "yes" ] ; then
-	CPPFLAGS="$CPPFLAGS -g"
+	CPPFLAGS="$CPPFLAGS -g -O0"
 	wxconfig="wxgtkd-config"
    debugstring="debugging"
+else
+   CPPFLAGS="$CPPFLAGS -O3"
 fi
 
 # Extract the first word of "$wxconfig", so it can be a program name with args.
 set dummy $wxconfig; ac_word=$2
-echo "$as_me:3276: checking for $ac_word" >&5
+echo "$as_me:3278: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_WX_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3290,7 +3292,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_WX_CONFIG="$ac_dir/$ac_word"
-   echo "$as_me:3293: found $ac_dir/$ac_word" >&5
+   echo "$as_me:3295: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -3302,10 +3304,10 @@ fi
 WX_CONFIG=$ac_cv_path_WX_CONFIG
 
 if test -n "$WX_CONFIG"; then
-  echo "$as_me:3305: result: $WX_CONFIG" >&5
+  echo "$as_me:3307: result: $WX_CONFIG" >&5
 echo "${ECHO_T}$WX_CONFIG" >&6
 else
-  echo "$as_me:3308: result: no" >&5
+  echo "$as_me:3310: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3315,7 +3317,7 @@ if [ "$WX_CONFIG" = "no" ] ; then
    echo "      1. wxWindows is installed (download from http://www.wxwindows.org)"
    echo "      2. the $debugstring libraries for wxWindows are installed"
    echo "      3. $wxconfig is on your path"
-   { { echo "$as_me:3318: error: *** Could not find $wxconfig" >&5
+   { { echo "$as_me:3320: error: *** Could not find $wxconfig" >&5
 echo "$as_me: error: *** Could not find $wxconfig" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3405,7 +3407,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3408: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3410: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3577,7 +3579,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3580: error: ambiguous option: $1
+    { { echo "$as_me:3582: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3596,7 +3598,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3599: error: unrecognized option: $1
+  -*) { { echo "$as_me:3601: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3633,7 +3635,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "configunix.h" ) CONFIG_HEADERS="$CONFIG_HEADERS configunix.h:configtemplate.h" ;;
-  *) { { echo "$as_me:3636: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3638: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3844,7 +3846,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3847: creating $ac_file" >&5
+    { echo "$as_me:3849: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3862,7 +3864,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3865: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3867: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3875,7 +3877,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3878: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3880: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3935,7 +3937,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3938: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3940: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3946,7 +3948,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3949: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3951: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3959,7 +3961,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3962: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3964: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4076,7 +4078,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4079: $ac_file is unchanged" >&5
+      { echo "$as_me:4081: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
