Configure script changes: - Code cleanup in configure.in. - PortAudio v19: Add alsa/jack libs if available. - Use system libid3tag if available.

diff --git a/sf-cvs/trunk/audacity-src/configure b/sf-cvs/trunk/audacity-src/configure
--- a/sf-cvs/trunk/audacity-src/configure
+++ b/sf-cvs/trunk/audacity-src/configure
@@ -313,7 +313,7 @@ ac_includes_default="\
 ac_subdirs_all="$ac_subdirs_all $CONFIG_SUBDIRS"
 ac_subdirs_all="$ac_subdirs_all [lib-src/portaudio-v19]"
 ac_subdirs_all="$ac_subdirs_all [lib-src/dlcompat]"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXCPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA BUILDLIBS EXTRAOBJS OPTOBJS CDEPEND AFTERBUILD INSTALL_PREFIX CONFIGHEADER LOCAL_LIBS AUDACITY_NAME PKG_CONFIG SNDFILE_CFLAGS SNDFILE_LIBS SAMPLERATE_CFLAGS SAMPLERATE_LIBS subdirs ZIP WX_CONFIG build build_cpu build_vendor build_os host host_cpu host_vendor host_os LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXCPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA BUILDLIBS EXTRAOBJS OPTOBJS CDEPEND AFTERBUILD INSTALL_PREFIX CONFIGHEADER LOCAL_LIBS AUDACITY_NAME PKG_CONFIG SNDFILE_CFLAGS SNDFILE_LIBS SAMPLERATE_CFLAGS SAMPLERATE_LIBS subdirs ZIP WX_CONFIG build build_cpu build_vendor build_os host host_cpu host_vendor host_os JACK_CFLAGS JACK_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4461,8 +4461,8 @@ fi
 echo "$as_me: FLAC libraries are available as system libraries" >&6;}
    else
       LIBFLAC_SYSTEM_AVAILABLE="no"
-      { echo "$as_me:$LINENO: FLAC libraries are NOT available as system libraries" >&5
-echo "$as_me: FLAC libraries are NOT available as system libraries" >&6;}
+      { echo "$as_me:$LINENO: FLAC/FLAC++ libraries are NOT available as system libraries" >&5
+echo "$as_me: FLAC/FLAC++ libraries are NOT available as system libraries" >&6;}
    fi
 
 
@@ -4937,15 +4937,17 @@ fi
    # I don't know if any released id3tag is sufficient, so disabling
    # system use for now...
 
-   #if test $libid3tag_found = yes && test $id3tag_h_found = yes ; then
-   #   LIBID3TAG_SYSTEM_AVAILABLE="yes"
-   #   LIBID3TAG_SYSTEM_LIBS=-lid3tag
-   #   LIBID3TAG_SYSTEM_CPPSYMBOLS="USE_LIBID3TAG"
-   #   AC_MSG_NOTICE([Libid3tag libraries are available as system libraries])
-   #else
+   if test $libid3tag_found = yes && test $id3tag_h_found = yes ; then
+      LIBID3TAG_SYSTEM_AVAILABLE="yes"
+      LIBID3TAG_SYSTEM_LIBS=-lid3tag
+      LIBID3TAG_SYSTEM_CPPSYMBOLS="USE_LIBID3TAG"
+      { echo "$as_me:$LINENO: Libid3tag libraries are available as system libraries" >&5
+echo "$as_me: Libid3tag libraries are available as system libraries" >&6;}
+   else
       LIBID3TAG_SYSTEM_AVAILABLE="no"
-   #   AC_MSG_NOTICE([Libid3tag libraries are NOT available as system libraries])
-   #fi
+      { echo "$as_me:$LINENO: Libid3tag libraries are NOT available as system libraries" >&5
+echo "$as_me: Libid3tag libraries are NOT available as system libraries" >&6;}
+   fi
 
 
    as_ac_File=`echo "ac_cv_file_${srcdir}/lib-src/libid3tag/frame.h" | $as_tr_sh`
@@ -5489,7 +5491,7 @@ if test "${with_ladspa+set}" = set; then
   withval="$with_ladspa"
   use_ladspa=$withval
 else
-  use_ladspa="default"
+  use_ladspa="yes"
 fi;
 
 
@@ -5693,68 +5695,16 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 
-if [ "$use_portaudio" = "v19" ] ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define USE_PORTAUDIO_V19 1
-_ACEOF
-
-
-   BUILDLIBS="$BUILDLIBS portaudio-v19/lib/libportaudio.a"
-   EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio-v19/lib/libportaudio.a"
-   CXXFLAGS="-I\$(top_srcdir)/lib-src/portaudio-v19/pa_common $CXXFLAGS"
-
-
-
-subdirs="$subdirs lib-src/portaudio-v19"
-
-
-else
-
-   CXXFLAGS="-I\$(top_srcdir)/lib-src/portaudio/pa_common $CXXFLAGS"
-
-   case "${host_os}" in
-     darwin* | rhapsody*)
-
-      CONFIGHEADER="configunix.h"
-
-
+case "${host_os}" in
+   darwin* | rhapsody*)
+            CONFIGHEADER="configunix.h"
       CXXFLAGS="-I../mac $CXXFLAGS"
-
-      BUILDLIBS="$BUILDLIBS portaudio/pa_mac_core/portaudio.a"
-      EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio/pa_mac_core/portaudio.a"
-
-      if [ "$use_portmixer" = "yes" ] ; then
-         BUILDLIBS="$BUILDLIBS portmixer/px_mac_core/portmixer.a"
-         EXTRAOBJS="$EXTRAOBJS ../lib-src/portmixer/px_mac_core/portmixer.a"
-      fi
-
-      LIBS="-framework AudioUnit -framework AudioToolbox $LIBS"
-      LIBS="-framework CoreAudio $LIBS -lz"
-
       AFTERBUILD="cp ../audacity ../Audacity.app && `$WX_CONFIG --rezflags` ../Audacity.app ../mac/audacity.r -c auDy && /Developer/Tools/SetFile -a avBstClinmed ../Audacity.app"
-
-      if [ "$use_ladspa" = "default" ] ; then
-         use_ladspa="yes";
-      fi
-
-                        ;;
+      ;;
 
    cygwin*)
-
-      BUILDLIBS="$BUILDLIBS portaudio/pa_win_wmme/portaudio.a"
-      EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio/pa_win_wmme/portaudio.a"
-      LIBS="$LIBS -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32 -lwsock32 -lwinmm"
+            LIBS="$LIBS -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32 -lwsock32 -lwinmm"
       CONFIGHEADER="configwin.h"
-
-      if [ "$use_portmixer" = "yes" ] ; then
-         BUILDLIBS="$BUILDLIBS portmixer/px_win_wmme/portmixer.a"
-         EXTRAOBJS="$EXTRAOBJS ../lib-src/portmixer/px_win_wmme/portmixer.a"
-      fi
-
-      if [ "$use_ladspa" = "default" ] ; then
-         use_ladspa="yes";
-      fi
 
 
 cat >>confdefs.h <<\_ACEOF
@@ -5771,25 +5721,248 @@ _ACEOF
       ;;
 
    *)
-
-      CONFIGHEADER="configunix.h"
-
-      BUILDLIBS="$BUILDLIBS portaudio/pa_unix_oss/portaudio.a"
-      EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio/pa_unix_oss/portaudio.a"
-
-      if [ "$use_portmixer" = "yes" ] ; then
-         BUILDLIBS="$BUILDLIBS portmixer/px_unix_oss/portmixer.a"
-         EXTRAOBJS="$EXTRAOBJS ../lib-src/portmixer/px_unix_oss/portmixer.a"
-      fi
-
-      if [ "$use_ladspa" = "default" ] ; then
-         use_ladspa="yes";
-      fi
-
+            CONFIGHEADER="configunix.h"
       AFTERBUILD=""
+esac
 
+
+if [ "$use_portaudio" = "v19" ] ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_PORTAUDIO_V19 1
+_ACEOF
+
+
+   BUILDLIBS="$BUILDLIBS portaudio-v19/lib/libportaudio.a"
+   EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio-v19/lib/libportaudio.a"
+   CXXFLAGS="-I\$(top_srcdir)/lib-src/portaudio-v19/pa_common $CXXFLAGS"
+
+
+
+subdirs="$subdirs lib-src/portaudio-v19"
+
+
+      case "${host_os}" in
+      darwin* | rhapsody*)
+         LIBS="-framework AudioUnit -framework AudioToolbox $LIBS"
+         LIBS="-framework CoreAudio $LIBS -lz"
+         ;;
+      cygwin*)
+         ;;
+      *)
+                  echo "$as_me:$LINENO: checking for snd_pcm_open in -lasound" >&5
+echo $ECHO_N "checking for snd_pcm_open in -lasound... $ECHO_C" >&6
+if test "${ac_cv_lib_asound_snd_pcm_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lasound  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char snd_pcm_open ();
+int
+main ()
+{
+snd_pcm_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_asound_snd_pcm_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_asound_snd_pcm_open=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_asound_snd_pcm_open" >&5
+echo "${ECHO_T}$ac_cv_lib_asound_snd_pcm_open" >&6
+if test $ac_cv_lib_asound_snd_pcm_open = yes; then
+  have_alsa=yes
+else
+  have_alsa=no
+fi
+
+         if [ $have_alsa = "yes" ] ; then
+            LIBS="$LIBS -lasound"
+         fi
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for jack" >&5
+echo $ECHO_N "checking for jack... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "jack" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking JACK_CFLAGS" >&5
+echo $ECHO_N "checking JACK_CFLAGS... $ECHO_C" >&6
+            JACK_CFLAGS=`$PKG_CONFIG --cflags "jack"`
+            echo "$as_me:$LINENO: result: $JACK_CFLAGS" >&5
+echo "${ECHO_T}$JACK_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking JACK_LIBS" >&5
+echo $ECHO_N "checking JACK_LIBS... $ECHO_C" >&6
+            JACK_LIBS=`$PKG_CONFIG --libs "jack"`
+            echo "$as_me:$LINENO: result: $JACK_LIBS" >&5
+echo "${ECHO_T}$JACK_LIBS" >&6
+        else
+            JACK_CFLAGS=""
+            JACK_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            JACK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "jack"`
+
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     have_jack=yes
+  else
+     have_jack=no
+  fi
+
+         if [ $have_jack = "yes" ] ; then
+            LIBS="$LIBS $JACK_LIBS"
+         fi
+         ;;
+   esac
+
+else
+      CXXFLAGS="-I\$(top_srcdir)/lib-src/portaudio/pa_common $CXXFLAGS"
+
+   case "${host_os}" in
+      darwin* | rhapsody*)
+         BUILDLIBS="$BUILDLIBS portaudio/pa_mac_core/portaudio.a"
+         EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio/pa_mac_core/portaudio.a"
+
+         LIBS="-framework AudioUnit -framework AudioToolbox $LIBS"
+         LIBS="-framework CoreAudio $LIBS -lz"
+         ;;
+      cygwin*)
+         BUILDLIBS="$BUILDLIBS portaudio/pa_win_wmme/portaudio.a"
+         EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio/pa_win_wmme/portaudio.a"
+         ;;
+      *)
+                  BUILDLIBS="$BUILDLIBS portaudio/pa_unix_oss/portaudio.a"
+         EXTRAOBJS="$EXTRAOBJS ../lib-src/portaudio/pa_unix_oss/portaudio.a"
+         ;;
    esac
 fi
+
+if [ "$use_portmixer" = "yes" ] ; then
+   case "${host_os}" in
+      darwin* | rhapsody*)
+         BUILDLIBS="$BUILDLIBS portmixer/px_mac_core/portmixer.a"
+         EXTRAOBJS="$EXTRAOBJS ../lib-src/portmixer/px_mac_core/portmixer.a"
+         ;;
+      cygwin*)
+         BUILDLIBS="$BUILDLIBS portmixer/px_win_wmme/portmixer.a"
+         EXTRAOBJS="$EXTRAOBJS ../lib-src/portmixer/px_win_wmme/portmixer.a"
+         ;;
+      *)
+                  BUILDLIBS="$BUILDLIBS portmixer/px_unix_oss/portmixer.a"
+         EXTRAOBJS="$EXTRAOBJS ../lib-src/portmixer/px_unix_oss/portmixer.a"
+         ;;
+   esac
+fi
+
 
 case "$host_os" in
    darwin* | rhapsody*)
@@ -5930,23 +6103,22 @@ fi
       ;;
 esac
 
+
 if [ "$use_ladspa" = "yes" ] ; then
    case "$host_os" in
       darwin* | rhapsody*)
-
-      LOCAL_LIBS="$LOCAL_LIBS libdl.a"
-      CXXFLAGS="$CXXFLAGS -I$(srcdir)/lib-src/dlcompat"
-      if test ! -f "lib-src/dlcompat/Makefile"; then
-         echo "--- Configuring dlcompat";
+         LOCAL_LIBS="$LOCAL_LIBS libdl.a"
+         CXXFLAGS="$CXXFLAGS -I$(srcdir)/lib-src/dlcompat"
+         if test ! -f "lib-src/dlcompat/Makefile"; then
+            echo "--- Configuring dlcompat";
 
 
 subdirs="$subdirs lib-src/dlcompat"
 
-      fi
-
-      ;;
-   *)
-      ;;
+         fi
+         ;;
+      *)
+         ;;
    esac
 fi
 
@@ -6131,7 +6303,6 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 fi
-
 
 
 case "${host_os}" in
@@ -6809,6 +6980,8 @@ s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
 s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
+s,@JACK_CFLAGS@,$JACK_CFLAGS,;t t
+s,@JACK_LIBS@,$JACK_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
