prevent PortAudio v19 and PortMixer from being used together

diff --git a/sf-cvs/trunk/audacity-src/configure b/sf-cvs/trunk/audacity-src/configure
--- a/sf-cvs/trunk/audacity-src/configure
+++ b/sf-cvs/trunk/audacity-src/configure
@@ -4300,6 +4300,12 @@ subdirs="$subdirs lib-src/soundtouch"
    fi
 fi
 
+if [ "$use_portmixer" = "yes" ] && [ "$use_portaudio" = "v19" ] ; then
+	{ { echo "$as_me:$LINENO: error: *** PortAudio v19 does not work with PortMixer (at least not yet) " >&5
+echo "$as_me: error: *** PortAudio v19 does not work with PortMixer (at least not yet) " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 if [ "$use_nyquist" = "yes" ] ; then
 
 cat >>confdefs.h <<\_ACEOF
